# -*- coding: utf-8 -*-
"""20_july.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_u8q5mp4pJdT6uPDXmtahm1jEUqBASsU
"""

list1 =["Asif","Khairul","Adnan"]
print (list1)
print (list1[1],list1 [-1])
print (list1[0:3:2])
print(list1[:1], list1[1:])


Courselist = ["AI", "ML", "DL", "OS", "R&I", "SAD", "economic"]
print(Courselist[-4:-1:2])
if "AI" in Courselist:
  print ("Yes, I am enrolled in AI course.")

Courselist[2]="SP-5"
print (Courselist)
Courselist[0:2] = ["Artificial Intelligence","Mechine learning"]
print (Courselist)
Courselist.insert(2,"Deep learning")
print (Courselist)
Courselist.remove("SP-5")
print (Courselist)
Courselist.append("Softwer Project - 5")
print (Courselist)

file = open("file.txt","a")
#print (file.read())
#print (file.read(14))
#print (file.read(4))
#print (file.readline())
#print (file.readline(4))
file.write(". Now I add a sentence here as a demo")
file.close()
file= open("file.txt","r")
print(file.read())

import os
if os.path.exists("demofile.txt"):
  os.remove("demofile.txt")
else:
  print("The file does not exist")
